name: meu_projeto_integrador
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.11

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  json_annotation: ^4.8.1

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.4
  equatable: ^2.0.5

  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  firebase_auth: ^4.14.4

  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^2.0.0

  mockito: ^5.4.2
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/placeholder_product.jpg
    - assets/carrossel.png
    - assets/carrossel2.png
    - assets/carrossel3.png
    - assets/escape.png
    - assets/led.png
    - assets/placeholder_product.jpg
    - assets/pneu.png
    - assets/suspensao.png
    - assets/tapete.png
    - assets/volante.png
    - assets/banco.png